//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AdmissionDetail
{
    public int id { get; set; }
    public int Uni_ID { get; set; }
    public string Criteria { get; set; }
    public string AdmissionDocuments { get; set; }
    public string FreeStructure { get; set; }

    public virtual University University { get; set; }
}

public partial class Application
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Application()
    {
        this.Payments = new HashSet<Payment>();
    }

    public int id { get; set; }
    public string UserID { get; set; }
    public string Region { get; set; }
    public Nullable<System.DateTime> SubmittedOn { get; set; }
    public string CurrentStatus { get; set; }
    public Nullable<int> UnivID { get; set; }
    public Nullable<int> deptID { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
    public virtual Department Department { get; set; }
    public virtual University University { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Payment> Payments { get; set; }
}

public partial class AspNetRole
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AspNetRole()
    {
        this.AspNetUsers = new HashSet<AspNetUser>();
    }

    public string Id { get; set; }
    public string Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
}

public partial class AspNetUser
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AspNetUser()
    {
        this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
        this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
        this.ContactInformations = new HashSet<ContactInformation>();
        this.Intermediate_Education = new HashSet<Intermediate_Education>();
        this.MakeChoices = new HashSet<MakeChoice>();
        this.Matriculation_Education = new HashSet<Matriculation_Education>();
        this.Media = new HashSet<Medium>();
        this.Personal_Details = new HashSet<Personal_Details>();
        this.Test_Results = new HashSet<Test_Results>();
        this.Contact_Us = new HashSet<Contact_Us>();
        this.UserProfiles = new HashSet<UserProfile>();
        this.AspNetRoles = new HashSet<AspNetRole>();
        this.Applications = new HashSet<Application>();
    }

    public string Id { get; set; }
    public string Email { get; set; }
    public bool EmailConfirmed { get; set; }
    public string PasswordHash { get; set; }
    public string SecurityStamp { get; set; }
    public string PhoneNumber { get; set; }
    public bool PhoneNumberConfirmed { get; set; }
    public bool TwoFactorEnabled { get; set; }
    public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
    public bool LockoutEnabled { get; set; }
    public int AccessFailedCount { get; set; }
    public string UserName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ContactInformation> ContactInformations { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Intermediate_Education> Intermediate_Education { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MakeChoice> MakeChoices { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Matriculation_Education> Matriculation_Education { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Medium> Media { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Personal_Details> Personal_Details { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Test_Results> Test_Results { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Contact_Us> Contact_Us { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UserProfile> UserProfiles { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Application> Applications { get; set; }
}

public partial class AspNetUserClaim
{
    public int Id { get; set; }
    public string UserId { get; set; }
    public string ClaimType { get; set; }
    public string ClaimValue { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
}

public partial class AspNetUserLogin
{
    public string LoginProvider { get; set; }
    public string ProviderKey { get; set; }
    public string UserId { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
}

public partial class C__MigrationHistory
{
    public string MigrationId { get; set; }
    public string ContextKey { get; set; }
    public byte[] Model { get; set; }
    public string ProductVersion { get; set; }
}

public partial class Campus
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Campus()
    {
        this.MakeChoices = new HashSet<MakeChoice>();
        this.Categories = new HashSet<Category>();
        this.Departments = new HashSet<Department>();
        this.CampusProfiles = new HashSet<CampusProfile>();
    }

    public int id { get; set; }
    public int Uni_ID { get; set; }
    public string Campus_Name { get; set; }
    public Nullable<bool> Status { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MakeChoice> MakeChoices { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Category> Categories { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Department> Departments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CampusProfile> CampusProfiles { get; set; }
    public virtual University University { get; set; }
}

public partial class CampusProfile
{
    public int id { get; set; }
    public int CampusID { get; set; }
    public string Contact1 { get; set; }
    public string Contact2 { get; set; }
    public string Contact3 { get; set; }
    public string Email { get; set; }
    public string Address { get; set; }
    public string AdminRatings { get; set; }
    public string ProspectusLink { get; set; }
    public Nullable<bool> MainCampus { get; set; }

    public virtual Campus Campus { get; set; }
}

public partial class Category
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Category()
    {
        this.ProgrammCategories = new HashSet<ProgrammCategory>();
    }

    public int id { get; set; }
    public string Category_Name { get; set; }
    public int CampusID { get; set; }

    public virtual Campus Campus { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProgrammCategory> ProgrammCategories { get; set; }
}

public partial class Contact_Us
{
    public int id { get; set; }
    public string User_ID { get; set; }
    public string User_Email { get; set; }
    public string Message { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
}

public partial class ContactInformation
{
    public int id { get; set; }
    public string User_ID { get; set; }
    public string Current_Address { get; set; }
    public string Permanent_Address { get; set; }
    public string Email { get; set; }
    public string Landline { get; set; }
    public string Phone { get; set; }
    public string Phone_Father { get; set; }
    public string Zip { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
}

public partial class Department
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Department()
    {
        this.DepartmentProfiles = new HashSet<DepartmentProfile>();
        this.MakeChoices = new HashSet<MakeChoice>();
        this.Programms = new HashSet<Programm>();
        this.Applications = new HashSet<Application>();
    }

    public int id { get; set; }
    public string Department_Name { get; set; }
    public Nullable<bool> Status { get; set; }
    public int CampusID { get; set; }

    public virtual Campus Campus { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DepartmentProfile> DepartmentProfiles { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MakeChoice> MakeChoices { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Programm> Programms { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Application> Applications { get; set; }
}

public partial class DepartmentProfile
{
    public int id { get; set; }
    public int DepartmentID { get; set; }
    public string ApplicationFee { get; set; }
    public string Criteria { get; set; }
    public string AdmissionDocs { get; set; }

    public virtual Department Department { get; set; }
}

public partial class Document
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Document()
    {
        this.TestResult_Document = new HashSet<TestResult_Document>();
    }

    public int id { get; set; }
    public string documentName { get; set; }
    public string documentURL { get; set; }
    public int userDetailID { get; set; }
    public string documentType { get; set; }
    public int documentSizeInKB { get; set; }

    public virtual Personal_Details Personal_Details { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TestResult_Document> TestResult_Document { get; set; }
}

public partial class Intermediate_Education
{
    public int id { get; set; }
    public string User_ID { get; set; }
    public string Board { get; set; }
    public string Rollno { get; set; }
    public string Passing_Year { get; set; }
    public string Total_Marks { get; set; }
    public string Obtained_Marks { get; set; }
    public string Percentage { get; set; }
    public string Division { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
}

public partial class MakeChoice
{
    public int id { get; set; }
    public string User_ID { get; set; }
    public int Uni_ID { get; set; }
    public int Campus_Id { get; set; }
    public int Department_Id { get; set; }
    public int Programm_Id { get; set; }
    public int Category_Id { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
    public virtual Campus Campus { get; set; }
    public virtual Department Department { get; set; }
    public virtual Programm Programm { get; set; }
    public virtual ProgrammCategory ProgrammCategory { get; set; }
    public virtual University University { get; set; }
}

public partial class Matriculation_Education
{
    public int id { get; set; }
    public string User_ID { get; set; }
    public string Board { get; set; }
    public string Rollno { get; set; }
    public string Passing_Year { get; set; }
    public string Total_Marks { get; set; }
    public string Obtained_Marks { get; set; }
    public string Percentage { get; set; }
    public string Division { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
}

public partial class Medium
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Medium()
    {
        this.UniversityProfiles = new HashSet<UniversityProfile>();
    }

    public int id { get; set; }
    public string User_ID { get; set; }
    public string Path { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UniversityProfile> UniversityProfiles { get; set; }
}

public partial class Payment
{
    public int id { get; set; }
    public string TrackingID { get; set; }
    public int AppID { get; set; }

    public virtual Application Application { get; set; }
}

public partial class Personal_Details
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Personal_Details()
    {
        this.Documents = new HashSet<Document>();
    }

    public int id { get; set; }
    public string User_ID { get; set; }
    public string Name { get; set; }
    public string Father_Name { get; set; }
    public string CNIC { get; set; }
    public string Father_CNIC { get; set; }
    public Nullable<System.DateTime> DOB { get; set; }
    public string Nationality { get; set; }
    public string Application_ID { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Document> Documents { get; set; }
}

public partial class Portfolio
{
    public int id { get; set; }
    public int Uni_ID { get; set; }
    public string Contact1 { get; set; }
    public string Contact2 { get; set; }
    public string Contact3 { get; set; }
    public string Contact4 { get; set; }
    public string Email { get; set; }
    public string Address { get; set; }
    public string Category { get; set; }

    public virtual University University { get; set; }
}

public partial class Programm
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Programm()
    {
        this.MakeChoices = new HashSet<MakeChoice>();
        this.ProgrammCategories = new HashSet<ProgrammCategory>();
    }

    public int id { get; set; }
    public int Department_ID { get; set; }
    public string Program_Name { get; set; }
    public Nullable<bool> Status { get; set; }

    public virtual Department Department { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MakeChoice> MakeChoices { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProgrammCategory> ProgrammCategories { get; set; }
}

public partial class ProgrammCategory
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProgrammCategory()
    {
        this.MakeChoices = new HashSet<MakeChoice>();
    }

    public int id { get; set; }
    public int Category_ID { get; set; }
    public int Programm_ID { get; set; }

    public virtual Category Category { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MakeChoice> MakeChoices { get; set; }
    public virtual Programm Programm { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class Test_Results
{
    public int id { get; set; }
    public string User_ID { get; set; }
    public string Test_Name { get; set; }
    public string Board { get; set; }
    public string Rollno { get; set; }
    public string Passing_Year { get; set; }
    public string Total_Marks { get; set; }
    public string Obtained_Marks { get; set; }
    public string Percentage { get; set; }
    public string Division { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
}

public partial class TestResult_Document
{
    public int id { get; set; }
    public int documentID { get; set; }
    public int UniID { get; set; }

    public virtual Document Document { get; set; }
}

public partial class University
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public University()
    {
        this.AdmissionDetails = new HashSet<AdmissionDetail>();
        this.Campuses = new HashSet<Campus>();
        this.MakeChoices = new HashSet<MakeChoice>();
        this.Portfolios = new HashSet<Portfolio>();
        this.University_Tests = new HashSet<University_Tests>();
        this.UniversityProfiles = new HashSet<UniversityProfile>();
        this.UniversityMedias = new HashSet<UniversityMedia>();
        this.Applications = new HashSet<Application>();
    }

    public int id { get; set; }
    public string Name { get; set; }
    public Nullable<System.DateTime> last_updated { get; set; }
    public string updated_by { get; set; }
    public Nullable<bool> Status { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AdmissionDetail> AdmissionDetails { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Campus> Campuses { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MakeChoice> MakeChoices { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Portfolio> Portfolios { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<University_Tests> University_Tests { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UniversityProfile> UniversityProfiles { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UniversityMedia> UniversityMedias { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Application> Applications { get; set; }
}

public partial class University_Tests
{
    public int id { get; set; }
    public int Uni_ID { get; set; }
    public string Test_Name { get; set; }

    public virtual University University { get; set; }
}

public partial class UniversityMedia
{
    public int id { get; set; }
    public int UniversityId { get; set; }
    public string Path { get; set; }

    public virtual University University { get; set; }
}

public partial class UniversityProfile
{
    public int id { get; set; }
    public int UniversityID { get; set; }
    public string Contact1 { get; set; }
    public string Contact2 { get; set; }
    public string Contact3 { get; set; }
    public string Email { get; set; }
    public string Address { get; set; }
    public string Type { get; set; }
    public string HecRanking { get; set; }
    public string TestName { get; set; }
    public Nullable<int> LogoAttachment { get; set; }
    public string FeeStructure { get; set; }
    public Nullable<bool> AdmissionOpen { get; set; }
    public Nullable<System.DateTime> LastDate { get; set; }
    public Nullable<bool> ApplicationFeeSame { get; set; }
    public string ApplicationFee { get; set; }
    public string Criteria { get; set; }
    public string About { get; set; }
    public string AdmisssionDocs { get; set; }

    public virtual Medium Medium { get; set; }
    public virtual University University { get; set; }
}

public partial class UserActivation
{
    public string UserId { get; set; }
    public System.Guid ActivationCode { get; set; }
}

public partial class UserProfile
{
    public int ID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Phone { get; set; }
    public string City { get; set; }
    public string AspNetUserID { get; set; }
    public string Email { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
}
