//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AdmissionDetail
{
    public int id { get; set; }
    public int Uni_ID { get; set; }
    public string Criteria { get; set; }
    public string AdmissionDocuments { get; set; }
    public string FreeStructure { get; set; }

    public virtual University University { get; set; }
}

public partial class Application
{
    public int id { get; set; }
    public string UserID { get; set; }
    public string Region { get; set; }
    public Nullable<System.DateTime> SubmittedOn { get; set; }
    public string CurrentStatus { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
}

public partial class AspNetRole
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AspNetRole()
    {
        this.AspNetUsers = new HashSet<AspNetUser>();
    }

    public string Id { get; set; }
    public string Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
}

public partial class AspNetUser
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AspNetUser()
    {
        this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
        this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
        this.AspNetRoles = new HashSet<AspNetRole>();
        this.Applications = new HashSet<Application>();
    }

    public string Id { get; set; }
    public string Email { get; set; }
    public bool EmailConfirmed { get; set; }
    public string PasswordHash { get; set; }
    public string SecurityStamp { get; set; }
    public string PhoneNumber { get; set; }
    public bool PhoneNumberConfirmed { get; set; }
    public bool TwoFactorEnabled { get; set; }
    public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
    public bool LockoutEnabled { get; set; }
    public int AccessFailedCount { get; set; }
    public string UserName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Application> Applications { get; set; }
}

public partial class AspNetUserClaim
{
    public int Id { get; set; }
    public string UserId { get; set; }
    public string ClaimType { get; set; }
    public string ClaimValue { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
}

public partial class AspNetUserLogin
{
    public string LoginProvider { get; set; }
    public string ProviderKey { get; set; }
    public string UserId { get; set; }

    public virtual AspNetUser AspNetUser { get; set; }
}

public partial class C__MigrationHistory
{
    public string MigrationId { get; set; }
    public string ContextKey { get; set; }
    public byte[] Model { get; set; }
    public string ProductVersion { get; set; }
}

public partial class Campus
{
    public int id { get; set; }
    public int Uni_ID { get; set; }
    public string Campus_Name { get; set; }

    public virtual University University { get; set; }
}

public partial class Category
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Category()
    {
        this.ProgrammCategories = new HashSet<ProgrammCategory>();
    }

    public int id { get; set; }
    public int Uni_ID { get; set; }
    public string Category_Name { get; set; }

    public virtual University University { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProgrammCategory> ProgrammCategories { get; set; }
}

public partial class Department
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Department()
    {
        this.Programms = new HashSet<Programm>();
        this.ProgrammCategories = new HashSet<ProgrammCategory>();
    }

    public int id { get; set; }
    public int Uni_ID { get; set; }
    public string Department_Name { get; set; }

    public virtual University University { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Programm> Programms { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProgrammCategory> ProgrammCategories { get; set; }
}

public partial class Portfolio
{
    public int id { get; set; }
    public int Uni_ID { get; set; }
    public string Contact1 { get; set; }
    public string Contact2 { get; set; }
    public string Contact3 { get; set; }
    public string Contact4 { get; set; }
    public string Email { get; set; }
    public string Address { get; set; }
    public string Category { get; set; }

    public virtual University University { get; set; }
}

public partial class Programm
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Programm()
    {
        this.ProgrammCategories = new HashSet<ProgrammCategory>();
    }

    public int id { get; set; }
    public int Uni_ID { get; set; }
    public int Department_ID { get; set; }
    public string Program_Name { get; set; }

    public virtual Department Department { get; set; }
    public virtual University University { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProgrammCategory> ProgrammCategories { get; set; }
}

public partial class ProgrammCategory
{
    public int id { get; set; }
    public int Uni_ID { get; set; }
    public int Department_ID { get; set; }
    public int Category_ID { get; set; }
    public int Programm_ID { get; set; }

    public virtual Category Category { get; set; }
    public virtual Department Department { get; set; }
    public virtual Programm Programm { get; set; }
    public virtual University University { get; set; }
}

public partial class University
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public University()
    {
        this.Portfolios = new HashSet<Portfolio>();
        this.AdmissionDetails = new HashSet<AdmissionDetail>();
        this.Categories = new HashSet<Category>();
        this.Departments = new HashSet<Department>();
        this.Programms = new HashSet<Programm>();
        this.ProgrammCategories = new HashSet<ProgrammCategory>();
        this.Campuses = new HashSet<Campus>();
    }

    public int id { get; set; }
    public string Name { get; set; }
    public Nullable<System.DateTime> last_updated { get; set; }
    public string updated_by { get; set; }
    public string data_progress { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Portfolio> Portfolios { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AdmissionDetail> AdmissionDetails { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Category> Categories { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Department> Departments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Programm> Programms { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProgrammCategory> ProgrammCategories { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Campus> Campuses { get; set; }
}
